language: node_js
node_js:
  - "7"
before_script:
- chmod +x ./prebuild.sh
- ./prebuild.sh
- gem install sass
- npm install
script:
- chmod +x ./deploy.sh
- npm run deploy
env:
  global:
  - GH_REPO="marabesi/twitter-clone-front-end"
branches:
  only:
  - master
after_script:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
