language: node_js
before_script:
- chmod +x ./prebuild.sh
- ./prebuild.sh
- gem install sass
script:
- webpack
env:
  global:
  - GH_REPO="marabesi/twitter-clone-front-end"
branches:
  only:
  - master
